sudo: false
language: rust

rust:
  - 1.20.0
  - stable
  - beta
  - nightly

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
