sudo: false
language: rust

rust:
  - 1.20.0
  - stable
  - beta
  - nightly

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build --verbose --manifest-path syn/Cargo.toml
  - cargo build --verbose --manifest-path syn/Cargo.toml --features parsing
  - cargo build --verbose --manifest-path syn/Cargo.toml --features printing
  - cargo build --verbose --manifest-path syn/Cargo.toml --features clone-impls
  - cargo build --verbose --manifest-path syn/Cargo.toml --features debug-impls
  - cargo build --verbose --manifest-path syn/Cargo.toml --features eq-impls
  - cargo build --verbose --manifest-path syn/Cargo.toml --features parsing,printing
  - cargo build --verbose --manifest-path syn/Cargo.toml --all-features

  - cargo test --verbose --manifest-path syn/Cargo.toml
  - cargo test --verbose --manifest-path syn/Cargo.toml --all-features
