(function() {var implementors = {};
implementors["either"] = [{text:"impl&lt;L:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>, R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"either/enum.Either.html\" title=\"enum either::Either\">Either</a>&lt;L, R&gt;",synthetic:false,types:["either::Either"]},];
implementors["proc_macro2"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"proc_macro2/struct.Span.html\" title=\"struct proc_macro2::Span\">Span</a>",synthetic:false,types:["proc_macro2::Span"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"proc_macro2/enum.Delimiter.html\" title=\"enum proc_macro2::Delimiter\">Delimiter</a>",synthetic:false,types:["proc_macro2::Delimiter"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"proc_macro2/enum.Spacing.html\" title=\"enum proc_macro2::Spacing\">Spacing</a>",synthetic:false,types:["proc_macro2::Spacing"]},];
implementors["tl_lang_syn"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"tl_lang_syn/cursor/struct.Cursor.html\" title=\"struct tl_lang_syn::cursor::Cursor\">Cursor</a>&lt;'a&gt;",synthetic:false,types:["tl_lang_syn::cursor::Cursor"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tl_lang_syn/punctuated/enum.TrailingPunctuation.html\" title=\"enum tl_lang_syn::punctuated::TrailingPunctuation\">TrailingPunctuation</a>",synthetic:false,types:["tl_lang_syn::punctuated::TrailingPunctuation"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tl_lang_syn/punctuated/enum.Count.html\" title=\"enum tl_lang_syn::punctuated::Count\">Count</a>",synthetic:false,types:["tl_lang_syn::punctuated::Count"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tl_lang_syn/punctuated/enum.Whitespace.html\" title=\"enum tl_lang_syn::punctuated::Whitespace\">Whitespace</a>",synthetic:false,types:["tl_lang_syn::punctuated::Whitespace"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"tl_lang_syn/span/struct.Span.html\" title=\"struct tl_lang_syn::span::Span\">Span</a>",synthetic:false,types:["tl_lang_syn::span::Span"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"tl_lang_syn/span/enum.SpanState.html\" title=\"enum tl_lang_syn::span::SpanState\">SpanState</a>",synthetic:false,types:["tl_lang_syn::span::SpanState"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
