(function() {var implementors = {};
implementors["tl_lang_syn"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>, P:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"tl_lang_syn/punctuated/enum.Pair.html\" title=\"enum tl_lang_syn::punctuated::Pair\">Pair</a>&lt;T, P&gt;",synthetic:false,types:["tl_lang_syn::punctuated::Pair"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>, P:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"tl_lang_syn/punctuated/struct.IntoPairs.html\" title=\"struct tl_lang_syn::punctuated::IntoPairs\">IntoPairs</a>&lt;T, P&gt;",synthetic:false,types:["tl_lang_syn::punctuated::IntoPairs"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"tl_lang_syn/punctuated/enum.TrailingPunctuation.html\" title=\"enum tl_lang_syn::punctuated::TrailingPunctuation\">TrailingPunctuation</a>",synthetic:false,types:["tl_lang_syn::punctuated::TrailingPunctuation"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"tl_lang_syn/punctuated/enum.Count.html\" title=\"enum tl_lang_syn::punctuated::Count\">Count</a>",synthetic:false,types:["tl_lang_syn::punctuated::Count"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"tl_lang_syn/punctuated/enum.Whitespace.html\" title=\"enum tl_lang_syn::punctuated::Whitespace\">Whitespace</a>",synthetic:false,types:["tl_lang_syn::punctuated::Whitespace"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"tl_lang_syn/span/struct.Span.html\" title=\"struct tl_lang_syn::span::Span\">Span</a>",synthetic:false,types:["tl_lang_syn::span::Span"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
